'use strict'; // ALWAYS


module.exports = Object.freeze([
    'camelcase', // eslint-recommended: "off",
    'complexity', // eslint-recommended: "off",
    'eqeqeq', // eslint-recommended: "off",
    'radix', // eslint-recommended: "off",
    'use-isnan', // eslint-recommended: "error",
    'consistent-return', // eslint-recommended: "off",
    'valid-typeof', // eslint-recommended: "error",
    'no-cond-assign', // eslint-recommended: "error",
    'no-dupe-keys', // eslint-recommended: "error",
    'no-func-assign', // eslint-recommended: "error",
    'no-extra-semi', // eslint-recommended: "error",
    'no-obj-calls', // eslint-recommended: "error",
    'no-debugger', // eslint-recommended: "error",
    'no-irregular-whitespace', // eslint-recommended: "error",
    'no-prototype-builtins', // eslint-recommended: "off",
    'default-case', // eslint-recommended: "off",
    'dot-notation', // eslint-recommended: "off",
    'guard-for-in', // eslint-recommended: "off",
    'no-alert', // eslint-recommended: "off",
    'no-caller', // eslint-recommended: "off",
    'no-eq-null', // eslint-recommended: "off",
    'no-extend-native', // eslint-recommended: "off",
    'no-fallthrough', // eslint-recommended: "error",
    'no-implied-eval', // eslint-recommended: "off",
    'no-labels', // eslint-recommended: "off",
    'no-loop-func', // eslint-recommended: "off",
    'no-multi-str', // eslint-recommended: "off",
    'no-global-assign', // eslint-recommended: "error",
    'no-redeclare', // eslint-recommended: "error",
    'no-script-url', // eslint-recommended: "off",
    'no-sequences', // eslint-recommended: "off",
    'no-with', // eslint-recommended: "off",
    'vars-on-top', // eslint-recommended: "off",
    'no-delete-var', // eslint-recommended: "error",
    'no-label-var', // eslint-recommended: "off",
    'no-shadow-restricted-names', // eslint-recommended: "error",
    'new-cap', // eslint-recommended: "off",
    'new-parens', // eslint-recommended: "off",
    'no-array-constructor', // eslint-recommended: "off",
    'no-lonely-if', // eslint-recommended: "off",
    'no-mixed-spaces-and-tabs', // eslint-recommended: "error",
    'no-new-object', // eslint-recommended: "off",
    'no-var', // eslint-recommended: "off",
    'no-plusplus', // eslint-recommended: "off",
    'no-floating-decimal', // eslint-recommended: "off",
    'no-else-return', // eslint-recommended: "off",
    'constructor-super', // eslint-recommended: "error",
    'getter-return', // eslint-recommended: "off",
    'no-buffer-constructor', // eslint-recommended: "off",
    'no-case-declarations', // eslint-recommended: "error",
    'no-class-assign', // eslint-recommended: "error",
    'no-compare-neg-zero', // eslint-recommended: "error",
    'no-const-assign', // eslint-recommended: "error",
    'no-constant-condition', // eslint-recommended: "error",
    'no-control-regex', // eslint-recommended: "error",
    'no-dupe-args', // eslint-recommended: "error",
    'no-dupe-class-members', // eslint-recommended: "error",
    'no-duplicate-case', // eslint-recommended: "error",
    'no-empty', // eslint-recommended: "error",
    'no-empty-character-class', // eslint-recommended: "error",
    'no-empty-pattern', // eslint-recommended: "error",
    'no-ex-assign', // eslint-recommended: "error",
    'no-extra-boolean-cast', // eslint-recommended: "error",
    'no-inner-declarations', // eslint-recommended: "error",
    'no-invalid-regexp', // eslint-recommended: "error",
    'no-new-symbol', // eslint-recommended: "error",
    'no-regex-spaces', // eslint-recommended: "error",
    'no-self-assign', // eslint-recommended: "error",
    'no-sparse-arrays', // eslint-recommended: "error",
    'no-this-before-super', // eslint-recommended: "error",
    'no-unexpected-multiline', // eslint-recommended: "error",
    'no-unsafe-finally', // eslint-recommended: "error",
    'no-unsafe-negation', // eslint-recommended: "error",
    'no-unused-labels', // eslint-recommended: "error",
    'no-useless-escape', // eslint-recommended: "error",
    'prefer-rest-params', // eslint-recommended: "off",
    'prefer-spread', // eslint-recommended: "off",
    'prefer-template', // eslint-recommended: "off",
    'require-yield', // eslint-recommended: "error",
    'semi-spacing', // eslint-recommended: "off",
    'semi-style', // eslint-recommended: "off",
    'symbol-description', // eslint-recommended: "off",
    'template-tag-spacing', // eslint-recommended: "off",
    'for-direction', // eslint-recommended: "off",
    'no-async-promise-executor',
    'no-loss-of-precision',
    'no-misleading-character-class',
    'no-nonoctal-decimal-escape',
    'require-atomic-updates',
    'require-unicode-regexp',
]);
