'use strict'; // ALWAYS


module.exports = Object.freeze([
    'no-process-env', // eslint-recommended: "off",
    'no-proto', // eslint-recommended: "off",
    'no-return-assign', // eslint-recommended: "off",
    'no-unused-expressions', // eslint-recommended: "off",
    'no-void', // eslint-recommended: "off",
    'no-warning-comments', // eslint-recommended: "off",
    'no-mixed-requires', // eslint-recommended: "off",
    'no-process-exit', // eslint-recommended: "off",
    'no-sync', // eslint-recommended: "off",
    'max-nested-callbacks', // eslint-recommended: "off",
    'no-inline-comments', // eslint-recommended: "off",
    'no-multiple-empty-lines', // eslint-recommended: "off",
    'no-nested-ternary', // eslint-recommended: "off",
    'no-space-before-semi', // eslint-recommended is missing this one,
    'no-spaced-func', // eslint-recommended: "off",
    'no-ternary', // eslint-recommended: "off",
    'no-trailing-spaces', // eslint-recommended: "off",
    'no-wrap-func', // eslint-recommended is missing this one,
    'operator-assignment', // eslint-recommended: "off",
    'padded-blocks', // eslint-recommended: "off",
    'sort-vars', // eslint-recommended: "off",
    'space-after-function-name', // eslint-recommended is missing this one,
    'space-after-keywords', // eslint-recommended is missing this one,
    'space-before-blocks', // eslint-recommended: "off",
    'space-in-brackets', // eslint-recommended is missing this one,
    'space-in-parens', // eslint-recommended: "off",
    'space-infix-ops', // eslint-recommended: "off",
    'space-return-throw-case', // eslint-recommended is missing this one,
    'space-unary-ops', // eslint-recommended: "off",
    'wrap-regex', // eslint-recommended: "off",
    'max-depth', // eslint-recommended: "off",
    'max-len', // eslint-recommended: "off",
    'max-statements', // eslint-recommended: "off",
    'array-bracket-spacing', // eslint-recommended: "off",
    'array-callback-return', // eslint-recommended: "off",
    'array-element-newline', // eslint-recommended: "off",
    'block-spacing', // eslint-recommended: "off",
    'callback-return', // eslint-recommended: "off",
    'capitalized-comments', // eslint-recommended: "off",
    'func-name-matching', // eslint-recommended: "off",
    'global-require', // eslint-recommended: "off",
    'id-blacklist', // eslint-recommended: "off",
    'id-length', // eslint-recommended: "off",
    'id-match', // eslint-recommended: "off",
    'indent-legacy', // eslint-recommended: "off",
    'jsx-quotes', // eslint-recommended: "off",
    'line-comment-position', // eslint-recommended: "off",
    'linebreak-style', // eslint-recommended: "off",
    'lines-around-comment', // eslint-recommended: "off",
    'lines-around-directive', // eslint-recommended: "off",
    'multiline-comment-style', // eslint-recommended: "off",
    'newline-after-var', // eslint-recommended: "off",
    'newline-before-return', // eslint-recommended: "off",
    'no-await-in-loop', // eslint-recommended: "off",
    'no-continue', // eslint-recommended: "off",
    'no-duplicate-imports', // eslint-recommended: "off",
    'no-extra-label', // eslint-recommended: "off",
    'no-extra-parens', // eslint-recommended: "off",
    'no-implicit-coercion', // eslint-recommended: "off",
    'no-iterator', // eslint-recommended: "off",
    'no-mixed-operators', // eslint-recommended: "off",
    'no-multi-assign', // eslint-recommended: "off",
    'no-native-reassign', // eslint-recommended: "off",
    'no-param-reassign', // eslint-recommended: "off",
    'no-restricted-globals', // eslint-recommended: "off",
    'no-restricted-imports', // eslint-recommended: "off",
    'no-restricted-modules', // eslint-recommended: "off",
    'no-restricted-properties', // eslint-recommended: "off",
    'no-tabs', // eslint-recommended: "off",
    'no-template-curly-in-string', // eslint-recommended: "off",
    'no-throw-literal', // eslint-recommended: "off",
    'no-useless-constructor', // eslint-recommended: "off",
    'no-useless-return', // eslint-recommended: "off",
    'object-property-newline', // eslint-recommended: "off",
    'one-var-declaration-per-line', // eslint-recommended: "off",
    'padding-line-between-statements', // eslint-recommended: "off",
    'prefer-promise-reject-errors', // eslint-recommended: "off",
    'prefer-reflect', // eslint-recommended: "off",
    'require-jsdoc', // eslint-recommended: "off",
    'sort-imports', // eslint-recommended: "off",
    'sort-keys', // eslint-recommended: "off",
    'template-curly-spacing', // eslint-recommended: "off",
    'unicode-bom', // eslint-recommended: "off",
    'valid-jsdoc', // eslint-recommended: "off",
    'no-confusing-arrow', // eslint-recommended: "off",
    'init-declarations', // eslint-recommended: "off",
    'default-case-last',
    'default-param-last',
    'function-call-argument-newline',
    'id-denylist',
    'array-bracket-newline',
    'no-promise-executor-return',
    'no-restricted-exports',
    'prefer-exponentiation-operator',
    'prefer-named-capture-group',
]);
