module.exports = Object.freeze([
    'no-console', // eslint-recommended: "error",
    'no-unreachable', // eslint-recommended: "error",
    'no-extra-bind', // eslint-recommended: "off",
    'no-lone-blocks', // eslint-recommended: "off",
    'no-multi-spaces', // eslint-recommended: "off",
    'no-new', // eslint-recommended: "off",
    'no-new-func', // eslint-recommended: "off",
    'no-new-wrappers', // eslint-recommended: "off",
    'no-octal', // eslint-recommended: "error",
    'no-octal-escape', // eslint-recommended: "off",
    'no-self-compare', // eslint-recommended: "off",
    'wrap-iife', // eslint-recommended: "off",
    'no-catch-shadow', // eslint-recommended: "off",
    'no-undef', // eslint-recommended: "error",
    'no-undef-init', // eslint-recommended: "off",
    'no-undefined', // eslint-recommended: "off",
    'no-unused-vars', // eslint-recommended: "error",
    'handle-callback-err', // eslint-recommended: "off",
    'no-new-require', // eslint-recommended: "off",
    'no-path-concat', // eslint-recommended: "off",
    'comma-style', // eslint-recommended: "off",
    'consistent-this', // eslint-recommended: "off",
    'eol-last', // eslint-recommended: "off",
    'func-names', // eslint-recommended: "off",
    'no-underscore-dangle', // eslint-recommended: "off",
    'no-bitwise', // eslint-recommended: "off",
    'arrow-spacing', // eslint-recommended: "off",
    'accessor-pairs', // eslint-recommended: "off",
    'block-scoped-var', // eslint-recommended: "off",
    'class-methods-use-this', // eslint-recommended: "off",
    'keyword-spacing', // eslint-recommended: "off",
    'max-statements-per-line', // eslint-recommended: "off",
    'no-div-regex', // eslint-recommended: "off",
    'no-empty-function', // eslint-recommended: "off",
    'no-implicit-globals', // eslint-recommended: "off",
    'no-invalid-this', // eslint-recommended: "off",
    'no-negated-condition', // eslint-recommended: "off",
    'no-negated-in-lhs', // eslint-recommended: "off",
    'no-return-await', // eslint-recommended: "off",
    'no-unmodified-loop-condition', // eslint-recommended: "off",
    'no-unneeded-ternary', // eslint-recommended: "off",
    'no-useless-call', // eslint-recommended: "off",
    'no-useless-computed-key', // eslint-recommended: "off",
    'no-useless-concat', // eslint-recommended: "off",
    'no-useless-rename', // eslint-recommended: "off",
    'no-whitespace-before-property', // eslint-recommended: "off",
    'object-shorthand', // eslint-recommended: "off",
    'prefer-arrow-callback', // eslint-recommended: "off",
    'prefer-const', // eslint-recommended: "off",
    'prefer-destructuring', // eslint-recommended: "off",
    'prefer-numeric-literals', // eslint-recommended: "off",
    'require-await', // eslint-recommended: "off",
    'switch-colon-spacing', // eslint-recommended: "off",
    'yield-star-spacing', // eslint-recommended: "off",
    'max-classes-per-file',
    'no-constructor-return',
    'no-dupe-else-if',
    'no-import-assign',
    'no-setter-return',
    'no-unreachable-loop',
    'no-unsafe-optional-chaining',
    'no-useless-backreference',
    'no-useless-catch',
    'prefer-object-spread',
]);
